### ISSUE TITLE
请问，可否直接使用 JS_TOOL 替代 jd-base 来运行您的MyAction 脚本库？

### ISSUE THREAD

**Issue by yasteora** [wuzhi04/jd-base#3]
这个是 JS_TOOL 
https://github.com/lan-tianxiang/JS_TOOL
它内置扫吗登陆，还有(bind mountpoint？)其脚本文件直接可以指定实际挂载位置，方便处理
还有其他好处，可否直接用人家现成的JS_TOOL 替代 该库？
JS_TOOL 可以指定 同步第三方脚本库 地址，我就是添加了您的MyAction库，运行下来似乎一切正常。

**Comment by wuzhi04** [comment]
感谢分享，最近太忙了脚本已经搞得晕头转向，我会仔细看看如果可以并且安全好用 可以采纳
