### ISSUE TITLE
内部账户之间不能肋力了，树叶大佬要怎么样才能解决？

### ISSUE THREAD

**Issue by tianchixia** [wuzhi04/jd-base#4]
## 如果启用了TempBlockCookie，那么只是被屏蔽的账号不助力其他账号，其他账号还是会助力被屏蔽的账号
AutoHelpOther="true"

把上面的删除，脚本还能运行，但是内部账户之间不能助力，树叶大佬要怎么样才能解决？

**Comment by wuzhi04** [comment]
MyXxxx系列变量需要填写，ForOtherXxxx系列变量仍然需要填写

**Comment by wuzhi04** [comment]
另外树叶已经退出维护，目前由wuzhi维护，且玩且珍惜，lxk已经退出后续何去何从还是未知数

**Comment by tianchixia** [comment]
好的，明白，如果没有新的大佬接盘的话，京豆会越来越少啦

wuzhi04 ***@***.***>于2021年6月12日 周六17:11写道：
